#%RAML 1.0 ResourceType
delete?:
  responses:
    200:
      body:
        application/json:
          type: types.OkStatus | string
  securedBy:
    - oauth_2_0:
        scopes: [<<scope>>]
post?:
  responses:
    200:
      body:
        application/json:
          type: types.OkStatus | string
  securedBy:
    - oauth_2_0:
        scopes: [<<scope>>]
securedBy:
  - oauth_2_0:
      scopes: [<<scope>>]
      #clientId: []
type: base
